export const EMPLOYEE_UPLOAD_REQUEST = 'EMPLOYEE_UPLOAD_REQUEST'
export const EMPLOYEE_UPLOAD_SUCCESS = 'EMPLOYEE_UPLOAD_SUCCESS'
export const EMPLOYEE_UPLOAD_FAIL = 'EMPLOYEE_UPLOAD_FAIL'
export const EMPLOYEE_UPLOAD_RESET = 'EMPLOYEE_UPLOAD_RESET'

export const EMPLOYEE_TASKS_REQUEST = 'EMPLOYEE_TASKS_REQUEST'
export const EMPLOYEE_TASKS_SUCCESS = 'EMPLOYEE_TASKS_SUCCESS'
export const EMPLOYEE_TAKS_FAIL = 'EMPLOYEE_TASKS_FAIL'
export const EMPLOYEE_TASKS_RESET = 'EMPLOYEE_TASKS_RESET'
