# Generated by Django 4.2.10 on 2024-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_employee_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
